### PR TITLE
Adds support for MacOSX

### LINKED ISSUE #65: Compile in xcode on 10.10?
Hi,
I am able to compile it in linux but not on my 10.10 mac. I already installed brew, added libcurl and libssl but I can't get Xcode to compile it. Error is:

Undefined symbols for architecture x86_64:
  "_pcre_compile", referenced from:
      _vg_regex_context_add_patterns in pattern.o
  "_pcre_exec", referenced from:
      _vg_regex_test in pattern.o
  "_pcre_free", referenced from:
      _vg_regex_context_add_patterns in pattern.o
      _vg_regex_context_clear_all_patterns in pattern.o
      _vg_regex_test in pattern.o
  "_pcre_study", referenced from:
      _vg_regex_context_add_patterns in pattern.o
  "_vg_ocl_context_free", referenced from:
      _main in oclvanitygen.o
  "_vg_ocl_context_new", referenced from:
      _main in oclvanityminer.o
      _main in oclvanitygen.o
  "_vg_ocl_context_new_from_devstr", referenced from:
      _main in oclvanityminer.o
      _main in oclvanitygen.o
  "_vg_ocl_enumerate_devices", referenced from:
      _main in oclvanityminer.o
      _main in oclvanitygen.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

What am I missing?

### PR DESCRIPTION
**Pull request by pendashteh**
Fixes #65

### CODE REVIEW

**Comment by kenorb** [comment]
- PR #55 and #75 implements the similar thing.
- Related issue: #103

**Comment by kenorb** [comment]
Fixed in: https://github.com/exploitagency/vanitygen-plus
