### ISSUE TITLE
Compiling oclvanityminer

### ISSUE THREAD

**Issue by exploitagency** [samr7/vanitygen#84]
Haven't looked into it yet but just thought I'd post this in case someone already figured it out.

make oclvanityminer
cc -O4 -march=native -Wall   -c -o oclvanityminer.o oclvanityminer.c
In file included from oclengine.h:22:0,
                 from oclvanityminer.c:32:
pattern.h:54:12: error: field ‘vxc_bntarg’ has incomplete type
  BIGNUM    vxc_bntarg;
            ^~~~~~~~~~
pattern.h:55:12: error: field ‘vxc_bnbase’ has incomplete type
  BIGNUM    vxc_bnbase;
            ^~~~~~~~~~
pattern.h:56:12: error: field ‘vxc_bntmp’ has incomplete type
  BIGNUM    vxc_bntmp;
            ^~~~~~~~~
pattern.h:57:12: error: field ‘vxc_bntmp2’ has incomplete type
  BIGNUM    vxc_bntmp2;
            ^~~~~~~~~~
<builtin>: recipe for target 'oclvanityminer.o' failed
make: *** [oclvanityminer.o] Error 1

**Comment by mautematico** [comment]
Exactly same error using gcc 4.8, 4.9, 5 and 6; on debian stretch

```
mautematico@delli:~/git/samr7/vanitygen$ make oclvanityminer
cc -ggdb -O3 -Wall   -c -o oclvanityminer.o oclvanityminer.c
In file included from oclengine.h:22:0,
                 from oclvanityminer.c:32:
pattern.h:54:12: error: field ‘vxc_bntarg’ has incomplete type
  BIGNUM    vxc_bntarg;
            ^~~~~~~~~~
pattern.h:55:12: error: field ‘vxc_bnbase’ has incomplete type
  BIGNUM    vxc_bnbase;
            ^~~~~~~~~~
pattern.h:56:12: error: field ‘vxc_bntmp’ has incomplete type
  BIGNUM    vxc_bntmp;
            ^~~~~~~~~
pattern.h:57:12: error: field ‘vxc_bntmp2’ has incomplete type
  BIGNUM    vxc_bntmp2;
            ^~~~~~~~~~
<integrado>: fallo en las instrucciones para el objetivo 'oclvanityminer.o'
make: *** [oclvanityminer.o] Error 1

```

**Comment by mautematico** [comment]
I think this guy is having similar issue:

http://pastebin.com/QYRrBMaC
http://pastebin.com/aZh1rMXU

**Comment by mautematico** [comment]
It is working on fresh ubuntu 14.04 docker image.
```
docker run -it ubuntu:14.04 bash

apt update
apt install git
apt install build-essential libtool autotools-dev autoconf libssl-dev libdb-dev libdb++-dev libboost-all-dev libpcre3 libpcre3-dev automake

git clone https://github.com/samr7/vanitygen
cd vanitygen
make
```

I suppose there are some issues with debian stretch package versions.
Anyway, it would be nice to fix those issues.

**Comment by exploitagency** [comment]
I found a fix, newer version of libssl-dev breaks it...
apt-get remove libssl-dev

For debian/kali

apt-get remove libssl-dev

You need these two dependencies
http://packages.ubuntu.com/trusty/libssl1.0.0
http://packages.ubuntu.com/trusty/zlib1g-dev

And this package
http://packages.ubuntu.com/trusty/libssl-dev

Click on amd64 or whatever architecture your on and then there is a download link that says security or mirror or some crap.  Copy the link and paste it after a wget, then do a dpkg -i whatever.deb.  It should make after you install those three.  zlib1g-dev gave me some problems, I think I had to run "apt-get -f install".

**Comment by exploitagency** [comment]
On Kali(Based on Debian Testing)
try:
apt-get install libssl1.0-dev

or

If it doesn't work try the below but be careful using remove, check that it doesn't take remove anything you need:
apt-get remove libssl-dev
apt-get install libssl1.0-dev

I believe the newer libssl-dev package breaks it.  I've had some success doing this method to get it to compile.  Although can anyone else verify this?  I haven't had any time to do real testing and I may have run a lot of extra commands as well that fixed the issue.

**Comment by baryluk** [comment]
I have the same issue on Debian sid. Both make and make oclvanityminer.

**Comment by exploitagency** [comment]
You can try my 64 bit binary for Debian Testing(Compiled on Intel I5 with GTX 1070's)
https://github.com/exploitagency/github-cryptocurrency/tree/master/root/cryptocurrency/vanity-addresses/bitcoin/samr7-vanitygen

or try fooling around with libssl1.0.0
wget PACKAGE.deb
dpkg -i MANUALLY-DOWNLOAD-PACKAGE

https://packages.debian.org/jessie/libssl-dev

**Comment by baryluk** [comment]
I was fine just doing apt-get install libssl1.0-dev:amd64, no issues.

I am just saying, out of the box I had the same problem as the author of the bug. It is not isolated.

**Comment by exploitagency** [comment]
Yeah its a common bug.  Glad that fixed it.

**Comment by exploitagency** [comment]
Yeah its a common bug with projects using that package.  Glad that solved your issue.

**Comment by baryluk** [comment]
Isn't this still a problem in the master branch tho, going forward? More and more distros will have issues, right? It is a bug in a vanitygen really, not in Debian, right?

**Comment by exploitagency** [comment]
Its a libssl-dev bug I believe regarding backwards compatibility, lots of projects I have messed with lately have the same issue.

**Comment by exploitagency** [comment]
Its a libssl-dev bug I believe regarding backwards compatibility, lots of projects I have messed with lately have the same issue.  I'll leave it open so dev can update code to work with new lib or others can see the quickfix.

**Comment by exploitagency** [comment]
For other OS

```
wget http://ftp.us.debian.org/debian/pool/main/g/glibc/libc6-udeb_2.24-9_amd64.udeb  
dpkg -i libc6-udeb_2.24-9_amd64.udeb  
wget http://ftp.us.debian.org/debian/pool/main/o/openssl1.0/libcrypto1.0.2-udeb_1.0.2k-1_amd64.udeb  
dpkg -i libcrypto1.0.2-udeb_1.0.2k-1_amd64.udeb  
rm libc6-udeb_2.24-9_amd64.udeb  
rm libcrypto1.0.2-udeb_1.0.2k-1_amd64.udeb  
```

**Comment by kenkit** [comment]
From my experience it's better you remove all openss-dev packages from your system, then install into /usr/local any version you want to test. I've managed to get things working with 1.02h after two whole days of messing with libssl-dev from the distro.
